#MKL_ROOT = /opt/intel/mkl/

FCC = gfortran
FFLAGS = -O3 -g -I xcfun/fortran -fopenmp -funroll-loops
#LIBS = -L$(MKL_ROOT)lib/intel64/ -lmkl_gf_lp64 -lmkl_sequential -lmkl_core \
-L./xcfun/lib -lxcfun -lopenblas
LIBS = -L./xcfun/lib -lxcfun -lopenblas

include Makefile.common
