MKL_ROOT = /opt/intel/oneapi/mkl/2025.3/

FCC = gfortran

#BLAS = $(shell pkg-config --libs openblas)
MKL_LIB = -L$(MKL_ROOT)lib/ -lmkl_gf_lp64 -lmkl_sequential -lmkl_core

XCFUN     = -I xcfun/fortran
XCFUN_LIB = -L./xcfun/lib/ -lxcfun

TREXIO         = $(shell pkg-config --cflags trexio)
TREXIO_LIB = $(shell pkg-config --libs trexio) -Wl,-rpath=$(shell pkg-config --variable=libdir trexio)

CHOLESKY       = -I ./gammcor-integrals/include
CHOLESKY_LIB   = ./gammcor-integrals/lib/cholesky.a

FFLAGS = $(XCFUN) $(TREXIO) $(CHOLESKY) -g -O3 -fopenmp -funroll-loops -ffree-line-length-none -std=legacy -DUSE_MKL_BATCH
#LIBS = $(BLAS) $(XCFUN_LIB) $(TREXIO_LIB)
LIBS = $(MKL_LIB) $(XCFUN_LIB) $(TREXIO_LIB) -Wl,--allow-multiple-definition $(CHOLESKY_LIB)

include Makefile.common

