S = SOURCE/
SS = SOURCE/sapt/
O = OBJ/

PROG = gammcor

OBJ = $(O)mainp.o $(O)initia.o $(O)dmscf.o $(O)misc.o $(O)optocc.o \
       $(O)eigenno.o $(O)optnorb.o\
       $(O)matvec.o $(O)hf.o $(O)matrix.o $(O)cpdmft.o \
       $(O)nonadia.o $(O)dftgrid.o $(O)lsd_sr.o $(O)dftfun_exerfpbe.o \
       $(O)dftfun_exerf.o $(O)dftfun_ecerfpbe.o $(O)dftfun_ecerf.o \
       $(O)dftacg_pw92c.o $(O)projector.o $(O)ekt.o \
       $(O)xcfun.o \
       $(O)gridmolpro.o \
       $(O)sorter.o $(O)tran.o $(O)systemdef.o \
       $(O)sorter_Cholesky.o \
       $(O)priunit.o $(O)rdwrext.o \
       $(O)globals.o $(O)types.o $(O)blocktypes.o $(O)memory.o \
       $(O)acpp_types.o $(O)sapt_files.o $(O)sapt_visual.o $(O)sapt_os.o \
       $(O)gammint.o $(O)CholeskyOTF.o $(O)interface_pp.o $(O)gridintern.o \
       $(O)inputfill.o $(O)abmats.o $(O)abfofo.o $(O)ab0fofo.o \
       $(O)abchol.o $(O)abcipsi.o \
       $(O)sapt_main.o $(O)sapt_exch.o $(O)sapt_exch_e1.o $(O)sapt_exch_os.o \
       $(O)sapt_pol.o $(O)sapt_elst.o $(O)sapt_ind.o $(O)sapt_utils.o \
       $(O)sapt_response.o $(O)sapt_interface.o \
       $(O)sapt_interface_chol.o $(O)sapt_interface_io.o \
       $(O)sapt_Chol_pol.o $(O)sapt_Chol_basic.o $(O)sapt_Chol_Cmat.o $(O)sapt_Chol_exch.o \
       $(O)exmisc.o $(O)exdpino.o $(O)exi.o $(O)exappr.o \
       $(O)srefex.o $(O)diis.o \
       $(O)timing.o \
       $(O)srlrdynamic.o $(O)erpa.o $(O)interpa.o  $(O)exact2el.o $(O)optapsg.o $(O)newton.o $(O)acfd.o $(O)accas.o \
       $(O)caspidft.o $(O)ac_exact_2el.o $(O)vv10.o \
       $(O)arithmetic.o $(O)io.o $(O)clock.o $(O)string.o $(O)sort.o $(O)display.o $(O)fofo_data.o $(O)chol_data.o $(O)batch_dgemm.o $(O)Cholesky.o $(O)Cholesky_old.o $(O)tran_Chol.o \
       $(O)iter_stats.o $(O)C_integrator.o $(O)iter_algorithm.o $(O)iter_algorithm_diis.o $(O)iter_algorithm_damping.o \
       $(O)lambda_calculator.o $(O)lambda_calculator_diag.o $(O)lambda_calculator_block.o $(O)lambda_calculator_projector.o \
       $(O)ac_iter.o $(O)ac_fofo.o \
       $(O)trexio_module.o $(O)write_trexio.o\
       $(O)git_info.o $(O)build_info.o

XOBJ = xcfun/fortran/xcfun_module.o xcfun/fortran/xcfun_autogen.o

$(O)%.o : $(S)%.F90
	$(FCC) -c -o $@ $< $(FFLAGS)
$(O)%.o : $(S)%.f90
	$(FCC) -c -o $@ $< $(FFLAGS)
$(O)%.o : $(S)%.f
	$(FCC) -c -o $@ $< $(FFLAGS)
$(O)%.o : $(SS)%.f90
	$(FCC) -c -o $@ $< $(FFLAGS)

$(PROG) : $(OBJ)
	$(FCC) -o $@ $^ $(XOBJ) $(FFLAGS) $(LIBS)

$(O)globals.o          :
$(O)memory.o           :
$(O)acpp_types.o       : $(O)types.o
$(O)sapt_files.o       :
$(O)sapt_visual.o      : $(O)types.o
$(O)sapt_os.o          : $(O)types.o $(O)sapt_utils.o
$(O)mainp.o            : $(S)commons.inc $(O)globals.o $(O)types.o $(O)inputfill.o $(O)systemdef.o $(O)sapt_main.o $(O)git_info.o $(O)build_info.o $(O)memory.o $(O)acpp_types.o
$(O)initia.o           : $(S)commons.inc $(O)priunit.o $(O)timing.o $(O)rdwrext.o $(O)sorter.o $(O)abmats.o $(O)types.o $(O)tran.o $(O)trexio_module.o $(O)chol_data.o $(O)fofo_data.o
$(O)accas.o            : $(S)commons.inc $(O)priunit.o $(O)timing.o $(O)rdwrext.o $(O)sorter.o $(O)abmats.o $(O)abfofo.o $(O)ab0fofo.o
$(O)acfd.o             : $(S)commons.inc $(O)abmats.o $(O)abfofo.o  $(O)ab0fofo.o $(O)rdwrext.o
$(O)ac_iter.o          : $(S)commons.inc $(O)abmats.o $(O)abfofo.o $(O)chol_data.o $(O)fofo_data.o
$(O)interpa.o          : $(S)commons.inc $(O)abmats.o $(O)abfofo.o $(O)ab0fofo.o
$(O)dftgrid.o          : $(S)commons.inc $(O)abmats.o
$(O)caspidft.o         : $(S)commons.inc $(O)rdwrext.o
$(O)ac_exact_2el.o     : $(S)commons.inc
$(O)cpdmft.o           : $(S)commons.inc
$(O)dmscf.o            : $(S)commons.inc
$(O)eigenno.o          : $(S)commons.inc
$(O)ekt.o              : $(S)commons.inc
$(O)erpa.o             : $(S)commons.inc
$(O)exact2el.o         : $(S)commons.inc
$(O)misc.o             : $(S)commons.inc
$(O)newton.o           : $(S)commons.inc
$(O)nonadia.o          : $(S)commons.inc
$(O)optapsg.o          : $(S)commons.inc
$(O)optnorb.o          : $(S)commons.inc
$(O)optocc.o           : $(S)commons.inc
$(O)projector.o        : $(S)commons.inc
$(O)srlrdynamic.o      : $(S)commons.inc
$(O)vv10.o             : $(S)commons.inc

$(O)ac_fofo.o          : $(O)abmats.o $(O)abfofo.o $(O)blocktypes.o \
                         $(O)C_integrator.o $(O)iter_algorithm.o $(O)iter_algorithm_diis.o $(O)iter_algorithm_damping.o \
                         $(O)lambda_calculator.o $(O)lambda_calculator_diag.o $(O)lambda_calculator_block.o $(O)lambda_calculator_projector.o
$(O)write_trexio.o     : $(O)trexio_module.o $(O)blocktypes.o $(O)priunit.o $(O)rdwrext.o $(O)tran.o

$(O)types.o            : $(O)priunit.o
$(O)diis.o             : $(O)priunit.o
$(O)inputfill.o        : $(O)types.o $(O)priunit.o
$(O)systemdef.o        : $(O)types.o $(O)fofo_data.o
$(O)rdwrext.o          : $(O)priunit.o $(O)trexio_module.o
$(O)sorter.o           : $(O)priunit.o $(O)rdwrext.o $(O)trexio_module.o
$(O)sorter_Cholesky.o  : $(O)priunit.o $(O)rdwrext.o $(O)trexio_module.o
$(O)batch_dgemm.o      :
$(O)tran.o             : $(O)blocktypes.o $(O)sorter.o $(O)batch_dgemm.o
$(O)tran_Chol.o        : $(O)tran.o
$(O)CholeskyOTF.o      : $(O)priunit.o $(O)tran.o
$(O)gammint.o          : $(O)CholeskyOTF.o
$(O)interface_pp.o     : $(O)acpp_types.o $(O)gammint.o
$(O)gridintern.o       : $(O)gammint.o
$(O)abfofo.o           : $(O)priunit.o $(O)tran.o $(O)blocktypes.o $(O)abchol.o $(O)timing.o $(O)fofo_data.o
$(O)abmats.o           : $(O)priunit.o $(O)tran.o
$(O)ab0fofo.o          : $(O)priunit.o $(O)tran.o $(O)blocktypes.o $(O)abfofo.o $(O)chol_data.o $(O)fofo_data.o
$(O)abchol.o           : $(O)chol_data.o
$(O)abcipsi.o          : $(O)abfofo.o

$(O)clock.o            : $(O)arithmetic.o
$(O)string.o           : $(O)arithmetic.o
$(O)display.o          : $(O)arithmetic.o $(O)string.o
$(O)io.o               : $(O)arithmetic.o $(O)display.o
$(O)Cholesky_old.o     : $(O)arithmetic.o $(O)io.o $(O)clock.o $(O)string.o $(O)sort.o $(O)display.o $(O)sorter.o
$(O)Cholesky.o        : $(O)arithmetic.o $(O)io.o $(O)clock.o $(O)string.o $(O)sort.o $(O)display.o $(O)sorter.o
# Cholesky module also provided by gammcor-integrals library (--allow-multiple-definition resolves conflicts)

$(O)sapt_utils.o       : $(O)types.o $(O)tran.o $(O)diis.o $(O)iter_stats.o $(O)abfofo.o
$(O)sapt_interface.o   : $(O)types.o $(O)timing.o \
                         $(O)sorter.o $(O)tran.o $(O)CholeskyOTF.o $(O)Cholesky_old.o $(O)abmats.o $(O)rdwrext.o $(O)trexio_module.o \
                         $(O)gammint.o $(O)tran_Chol.o \
                         $(O)sapt_interface_chol.o $(O)sapt_interface_io.o
$(O)sapt_elst.o        : $(O)types.o $(O)sapt_utils.o
$(O)sapt_ind.o         : $(O)types.o $(O)tran.o $(O)sapt_utils.o $(O)rdwrext.o
$(O)sapt_pol.o         : $(O)types.o $(O)tran.o $(O)sapt_utils.o $(O)rdwrext.o $(O)sapt_elst.o $(O)sapt_ind.o
$(O)sapt_exch_e1.o     : $(O)types.o $(O)tran.o $(O)sapt_utils.o $(O)exmisc.o $(O)exi.o
$(O)sapt_exch_os.o     : $(O)types.o $(O)tran.o $(O)sapt_utils.o $(O)exmisc.o $(O)exi.o
$(O)sapt_exch.o        : $(O)types.o $(O)tran.o $(O)timing.o $(O)sapt_utils.o $(O)exmisc.o $(O)exi.o $(O)exappr.o $(O)srefex.o \
                         $(O)sapt_exch_e1.o $(O)sapt_exch_os.o
$(O)sapt_interface_chol.o : $(O)types.o $(O)timing.o $(O)tran.o $(O)sorter.o $(O)tran_Chol.o $(O)gammint.o
$(O)sapt_interface_io.o   : $(O)types.o $(O)timing.o $(O)tran.o $(O)sorter.o $(O)tran_Chol.o \
                            $(O)gammint.o $(O)rdwrext.o $(O)trexio_module.o
$(O)sapt_Chol_basic.o  : $(O)tran.o $(O)sapt_utils.o $(O)timing.o
$(O)sapt_Chol_Cmat.o   : $(O)tran.o $(O)sapt_utils.o $(O)timing.o \
                         $(O)iter_stats.o $(O)iter_algorithm.o $(O)iter_algorithm_diis.o \
                         $(O)lambda_calculator.o $(O)lambda_calculator_diag.o $(O)lambda_calculator_projector.o
$(O)sapt_Chol_pol.o    : $(O)tran.o $(O)sapt_utils.o $(O)timing.o \
                         $(O)sapt_Chol_basic.o $(O)sapt_Chol_Cmat.o
$(O)sapt_Chol_exch.o   : $(O)types.o $(O)rdwrext.o $(O)sapt_utils.o
$(O)sapt_response.o    : $(O)types.o $(O)tran.o $(O)abmats.o $(O)abfofo.o $(O)ab0fofo.o $(O)abcipsi.o \
                         $(O)sapt_utils.o $(O)timing.o
$(O)sapt_main.o        : $(O)types.o \
                         $(O)sapt_pol.o $(O)sapt_exch.o $(O)sapt_Chol_pol.o $(O)sapt_Chol_exch.o \
                         $(O)sapt_utils.o $(O)exdpino.o \
                         $(O)sapt_response.o $(O)sapt_interface.o \
                         $(O)sapt_os.o $(O)sapt_visual.o $(O)sapt_files.o \
                         $(O)tran_Chol.o

$(O)exmisc.o           : $(O)types.o
$(O)exappr.o           : $(O)exmisc.o
$(O)srefex.o           : $(O)exmisc.o $(O)types.o
$(O)exdpino.o          : $(O)exmisc.o $(O)types.o $(O)tran.o $(O)timing.o $(O)sapt_utils.o

$(O)iter_algorithm.o              : $(O)iter_stats.o
$(O)iter_algorithm_diis.o         : $(O)iter_stats.o $(O)iter_algorithm.o $(O)diis.o
$(O)iter_algorithm_damping.o      : $(O)iter_stats.o $(O)iter_algorithm.o
$(O)lambda_calculator_diag.o      : $(O)lambda_calculator.o
$(O)lambda_calculator_block.o     : $(O)lambda_calculator.o $(O)abfofo.o
$(O)lambda_calculator_projector.o : $(O)lambda_calculator.o
$(O)C_integrator.o                : $(O)iter_stats.o $(O)iter_algorithm.o $(O)lambda_calculator.o

.PHONY : clean
clean :
	rm -f $(O)*.o *.mod $(PROG)

