module xcfun_autogen
! this file is generated by src/geninterface.cpp - do not edit
  implicit none
  integer, parameter :: XC_NR_PARAMS = 33
  integer, parameter :: XC_SLATERX = 1
  integer, parameter :: XC_VWN5C = 2
  integer, parameter :: XC_BECKEX = 3
  integer, parameter :: XC_BECKECORRX = 4
  integer, parameter :: XC_BECKESRX = 5
  integer, parameter :: XC_OPTX = 6
  integer, parameter :: XC_LYPC = 7
  integer, parameter :: XC_PBEX = 8
  integer, parameter :: XC_REVPBEX = 9
  integer, parameter :: XC_RPBEX = 10
  integer, parameter :: XC_PBEC = 11
  integer, parameter :: XC_SPBEC = 12
  integer, parameter :: XC_VWN_PBEC = 13
  integer, parameter :: XC_LDAERFX = 14
  integer, parameter :: XC_LDAERFC = 15
  integer, parameter :: XC_RANGESEP_MU = 16
  integer, parameter :: XC_KTX = 17
  integer, parameter :: XC_TFK = 18
  integer, parameter :: XC_PW91X = 19
  integer, parameter :: XC_PW91K = 20
  integer, parameter :: XC_PW92C = 21
  integer, parameter :: XC_M05X = 22
  integer, parameter :: XC_M05X2X = 23
  integer, parameter :: XC_M06X = 24
  integer, parameter :: XC_M06X2X = 25
  integer, parameter :: XC_M06LX = 26
  integer, parameter :: XC_M06HFX = 27
  integer, parameter :: XC_BRX = 28
  integer, parameter :: XC_M05X2C = 29
  integer, parameter :: XC_M05C = 30
  integer, parameter :: XC_M06C = 31
  integer, parameter :: XC_M06LC = 32
  integer, parameter :: XC_M06X2C = 33
end module
