# gammcor -- debug build (Intel ifx)
#
#   meson setup   build-debug --native-file .meson/profiles/ifx-debug.ini
#   meson compile -C build-debug
#

[binaries]
fortran = 'ifx'

[built-in options]
b_asneeded        = false

fortran_args      = ['-O0', '-g', '-traceback', '-check', 'all', '-qopenmp', '-coarray=single', '-assume', 'byterecl', '-heap-arrays', '-warn', 'nounused', '-qmkl=parallel']
fortran_link_args = ['-O0', '-g', '-traceback', '-check', 'all', '-qopenmp', '-coarray=single', '-qmkl=parallel', '-limf']

[properties]
profile  = 'debug'
exe_name = 'gammcor-debug'
