# gammcor -- production build (Intel ifx)
#
#   meson setup   build --native-file .meson/profiles/ifx.ini
#   meson compile -C build
#

[binaries]
fortran = 'ifx'

[built-in options]
fortran_args      = ['-O3', '-xHost', '-qopenmp', '-coarray=single', '-assume', 'byterecl', '-heap-arrays', '-warn', 'nounused', '-qmkl=parallel']
fortran_link_args = ['-O3', '-xHost', '-qopenmp', '-coarray=single', '-qmkl=parallel', '-limf']

[properties]
profile  = 'release'
exe_name = 'gammcor'
