function(init)
    list(LENGTH ARGV length)
    list(GET ARGV 0 key)
    list(GET ARGV 1 type)
    if(${length} GREATER 2)
        list(GET ARGV 2 value)
    endif()
    set(${key} ${value} CACHE ${type} "")
endfunction()