set(GAMMCOR_SOURCE
    SOURCE/abfofo.f90
    SOURCE/abmats.f90
    SOURCE/abchol.f90
    SOURCE/accas.f
    SOURCE/ac_exact_2el.f
    SOURCE/acfd.f
    SOURCE/ac_fofo.f90
    SOURCE/ac_iter.f
    SOURCE/caspidft.f
    SOURCE/constants.h
    SOURCE/cpdmft.f
    SOURCE/dftacg_pw92c.f
    SOURCE/dftfun_ecerf.f
    SOURCE/dftfun_ecerfpbe.f
    SOURCE/dftfun_exerf.f
    SOURCE/dftfun_exerfpbe.f
    SOURCE/dftgrid.f
    SOURCE/diis.f90
    SOURCE/dmscf.f
    SOURCE/eigenno.f
    SOURCE/ekt.f
    SOURCE/erpa.f
    SOURCE/exact2el.f
    SOURCE/exappr.f90
    SOURCE/exdpino.f90
    SOURCE/exi.f90
    SOURCE/exmisc.f90
    SOURCE/gridmolpro.f90
    SOURCE/hf.f
    SOURCE/initia.f
    SOURCE/inputfill.f90
    SOURCE/interpa.f
    SOURCE/lsd_sr.f
    SOURCE/mainp.f
    SOURCE/matrix.f
    SOURCE/matvec.f
    SOURCE/misc.f
    SOURCE/newton.f
    SOURCE/nonadia.f
    SOURCE/optapsg.f
    SOURCE/optnorb.f
    SOURCE/optocc.f
    SOURCE/projector.f
    SOURCE/sapt_exch.f90
    SOURCE/sapt_main.f90
    SOURCE/sapt_pol.f90
    SOURCE/sapt_utils.f90
    SOURCE/sorter.f90
    SOURCE/srefex.f90
    SOURCE/srlrdynamic.f
    SOURCE/systemdef.f90
    SOURCE/timing.f90
    SOURCE/tran.f90
    SOURCE/types.f90
    SOURCE/vv10.f
    SOURCE/xcfun.f90
    SOURCE/arithmetic.f90
    SOURCE/io.f90
    SOURCE/clock.f90
    SOURCE/string.f90
    SOURCE/sort.f90
    SOURCE/display.f90
    SOURCE/Cholesky.f90
    SOURCE/Cholesky_old.f90
    SOURCE/tran_Chol.f90
	SOURCE/iter_stats.f90
    SOURCE/C_integrator.f90
    SOURCE/iter_algorithm.f90
    SOURCE/iter_algorithm_diis.f90
    SOURCE/iter_algorithm_damping.f90
    SOURCE/lambda_calculator.f90
    SOURCE/lambda_calculator_diag.f90
    SOURCE/lambda_calculator_block.f90
    SOURCE/lambda_calculator_projector.f90
    SOURCE/ac_iter.f
    SOURCE/ac_fofo.f90
    SOURCE/sorter_Cholesky.f90
    SOURCE/sapt_Chol_pol.f90
    SOURCE/sapt_Chol_exch.f90
    SOURCE/ab0fofo.f90
    SOURCE/sapt_response.f90
    SOURCE/sapt_interface.f90
    SOURCE/priunit.f90
    SOURCE/rdwrext.f90
    SOURCE/blocktypes.f90
    SOURCE/rdmcorr.f90

    SOURCE/git_info.f90
    SOURCE/build_info.f90
    SOURCE/trexio_f.f90
)
