set(GAMMCOR_SOURCE
    SOURCE/abfofo.f90
    SOURCE/abmats.f90
    SOURCE/accas.f
    SOURCE/ac_exact_2el.f
    SOURCE/acfd.f
    SOURCE/ac_fofo.f90
    SOURCE/ac_iter.f
    SOURCE/caspidft.f
    SOURCE/constants.h
    SOURCE/cpdmft.f
    SOURCE/dftacg_pw92c.f
    SOURCE/dftfun_ecerf.f
    SOURCE/dftfun_ecerfpbe.f
    SOURCE/dftfun_exerf.f
    SOURCE/dftfun_exerfpbe.f
    SOURCE/dftgrid.f
    SOURCE/diis.f90
    SOURCE/dmscf.f
    SOURCE/eigenno.f
    SOURCE/ekt.f
    SOURCE/erpa.f
    SOURCE/exact2el.f
    SOURCE/exappr.f90
    SOURCE/exdpino.f90
    SOURCE/exi.f90
    SOURCE/exmisc.f90
    SOURCE/gridmolpro.f90
    SOURCE/hf.f
    SOURCE/initia.f
    SOURCE/inputfill.f90
    SOURCE/interpa.f
    SOURCE/lsd_sr.f
    SOURCE/mainp.f
    SOURCE/matrix.f
    SOURCE/matvec.f
    SOURCE/misc.f
    SOURCE/newton.f
    SOURCE/nonadia.f
    SOURCE/optapsg.f
    SOURCE/optnorb.f
    SOURCE/optocc.f
    SOURCE/projector.f
    SOURCE/sapt_exch.f90
    SOURCE/sapt_main.f90
    SOURCE/sapt_pol.f90
    SOURCE/sapt_utils.f90
    SOURCE/sorter.f90
    SOURCE/srefex.f90
    SOURCE/srlrdynamic.f
    SOURCE/systemdef.f90
    SOURCE/timing.f90
    SOURCE/tran.f90
    SOURCE/types.f90
    SOURCE/vv10.f
    SOURCE/xcfun.f90
    SOURCE/git_info.f90
    SOURCE/build_info.f90
)