C
      Common/MISCFL/ XELE,IFun,IFunSR,IFunSRKer,NELE,IRes,INO,IPrint,
     $ IInteg,IAO,IGVB,IDALTON,IFreeze,ILoc,NInActOrb,NActOrb,NVirtOrb
      Common/CAS/ ICASSCF,NAcCAS,NInAcCAS
      Common/BBC3/ IType(1000)
      Common/DFTSR/ Alpha,Cmix
      Common/Sym/ MxSym,FMultTab,NoSym
      Common/APSG/ IGem(1000),CICoef(1000)
      Common/EMBEDD/ IFlFrag1,IFrag,NGemSave,IAuxGem(1000),
     $ IGemSave(1000), IOrbA(1000),NGemB, NActive,IFlCore,IFl12,IFlSnd,
     $ IConnect(1000,1000)
C
